name: CI - Python App

# Trigger the workflow on push or pull request to 'main' or 'develop' branches
on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:  # Allow manual trigger from GitHub UI

# Set permissions for the workflow
permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"  # Updated to latest stable Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run code linting with flake8
        run: |
          # Fail on critical issues
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Report all lint warnings
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run tests with coverage
        run: |
          pytest --cov=. --cov-report=term-missing

      - name: Upload coverage report (optional)
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: .coverage
