name: Variable Scope Example

env:
  MY_WORKFLOW_VARIABLE: "This is a workflow-level variable"

on:
  push:
    branches:
      - main

jobs:
  test-scope:
    name: Variable Scope Demo

    env:
      MY_JOB_VARIABLE: "This is a job-level variable"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Step-level Variable Demo
        env:
          MY_STEP_VARIABLE: "This is a step-level variable"
        run: |
          echo "Workflow-level: $MY_WORKFLOW_VARIABLE"
          echo "Job-level: $MY_JOB_VARIABLE"
          echo "Step-level: $MY_STEP_VARIABLE"
      
      - name: Step without step-level variable
        run: |
          echo "Workflow-level: $MY_WORKFLOW_VARIABLE"
          echo "Job-level: $MY_JOB_VARIABLE"
          echo "Step-level (should be empty): $MY_STEP_VARIABLE"
